---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ing-api-call-sa
  #namespace: gitlab-managed-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ing-api-call-role
  #namespace: gitlab-managed-apps
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ing-api-call-roldbinding
  #namespace: gitlab-managed-apps
subjects:
  - kind: ServiceAccount
    name: ing-api-call-sa
roleRef:
  kind: Role
  name: ing-api-call-role
  apiGroup: rbac.authorization.k8s.io
